version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tvshows:/data/tvshows
      - /docker/plex/movies:/data/movies
      - /docker/plex/transcode:/transcode
    restart: unless-stopped
