version: "2"
services:
  emby:
    image: emby/embyserver
    container_name: emby
    network_mode: host
    ports:
      - 8096:8096
      # - 8920:8920 HTTPS
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=1000
    volumes:
      - /docker/emby/config:/config
      - /path/to/share1:/mnt/share1
    restart: unless-stopped
