version: '2'
services:
 minio:
  image: minio/minio:RELEASE.2019-04-23T23-50-36Z
  container_name: minio
  volumes:
   - /docker/minio/data:/data
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: admin
   MINIO_SECRET_KEY: appannie
  command: server /data
